FROM python:3.11-bookworm

RUN apt update && apt upgrade -y && \
  apt install -y \
  libopenblas-dev\
  ninja-build\
  build-essential\
  pkg-config\
  wget


ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080